const address = [
  {
    location: "Banepa",
    subLocation: [
      "28 Kilo Area",
      "Banepa Chowk Area",
      "Basghari Area",
      "Bhainsepati Area",
      "Budol Area",
      "Chandeshwori Temple Area",
      "Dhulikhel Area",
      "Kathmandu university Area",
      "Naya Basti Area",
      "Panauti Area",
      "Sanga",
      "Tindobato Area",
    ],
  },
  {
    location: "Bhaktapur",
    subLocation: [
      "Balkot Area",
      "Biruwa Buspark Area",
      "Bode",
      "Duwakot",
      "Gaththaghar Area",
      "Jagati Area",
      "Kamalbinayak Area",
      "Katunje Area",
      "Kausaltar Area",
      "Kharipati",
      "Lohakanthali Area",
      "New Thimi",
      "Old Thimi",
      "Palanse",
      "Sallaghari Area",
      "Sano Thimi Area",
      "Sirutar",
      "Suryabinayak Area",
    ],
  },
  {
    location: "Kathmandu Metro 10 - New Baneshwor Area",
    subLocation: [
      "Bijuli Bazar",
      "Buddhanagar",
      "New Baneshwor Chowk",
      "Ratna Rajya Area",
      "Shankhamul Area",
      "Thapagaun Area",
    ],
  },
  {
    location: "Kathmandu Metro 11 - Maitighar Area",
    subLocation: [
      "Babarmahal",
      "Maitighar",
      "Shahid Gate",
      "Thapathali",
      "Tripureshwor",
    ],
  },
  {
    location: "Kathmandu Metro 12 - Teku Area",
    subLocation: ["Teku"],
  },
  {
    location: "Kathmandu Metro 13 - Kalimati Area",
    subLocation: ["Bafal", "Kalimati", "Kharibot", "Soalteemode", "Tahachal"],
  },
  {
    location: "Kathmandu Metro 14 - Kuleshwor Area",
    subLocation: ["Balkhu", "Kalanki Chowk", "Kuleshwor", "Ravi Bhawan"],
  },
  {
    location: "Kathmandu Metro 15 - Swayambhu Area",
    subLocation: [
      "Bahiti",
      "Bijeshwori",
      "Chhauni",
      "Dallu",
      "Kimdol",
      "Sobhabhagawati",
      "Swayambhu - Bhagwan Pau",
    ],
  },
  {
    location: "Kathmandu Metro 16 - Nayabazar Area",
    subLocation: [
      "Balaju - Bypass",
      "Balaju Chauki",
      "Balaju Chowk",
      "Balaju - Machha Pokhari",
      "Banasthali",
      "Kaldhara",
      "Khusibu",
      "Paknajol",
      "People's Dental Campus Area",
      "Sorhakhutte",
    ],
  },
  {
    location: "Kathmandu Metro 9 - Sinamangal Area",
    subLocation: [
      "Airport",
      "Battisputali",
      "Gaurigaun",
      "Old Baneshwor",
      "Sinamangal",
      "Tilganga",
    ],
  },
  {
    location: "Kathmandu Metro 8 - Gaushala Area",
    subLocation: [
      "Gaurighat",
      "Gaushala",
      "Guhyeshwari",
      "Jayabageshwori",
      "Pashupathinath",
    ],
  },
  {
    location: "Kathmandu Metro 7 - Chabahil Area",
    subLocation: [
      "Chabahil Chowk",
      "Chuchepati",
      "Gangahiti",
      "Gopikrishna Hall Area",
      "Kalopul",
      "Kumarigal",
      "Kumaristhan",
      "Mitrapark",
      "Siphal",
    ],
  },
  {
    location: "Kathmandu Metro 5 - Tangal Area",
    subLocation: [
      "Bhatbhateni",
      "Handigaun",
      "Maligaun",
      "Sano Gaucharan",
      "Tangal",
    ],
  },
  {
    location: "Kathmandu Metro 4 - Bishalnagar Area",
    subLocation: [
      "Bishalnagar",
      "Chandol",
      "Chapal Karkhana",
      "Chun Devi",
      "Dhumbarahi Chowk",
      "Dhumbarahi Pipalbot",
      "Sukedhara",
    ],
  },
  {
    location: "Kathmandu Metro 3 - Maharajgunj Area",
    subLocation: ["Narayan Gopal Chowk Area", "Teaching Hospital"],
  },
];

export default address